const product = (item) => ({
  price: null,
  coverage: null,
  rating: null,
  reviews: 0,
  quality: 76,
  bathroom: false,
  madeInUSA: false,
  image: null,
  award: "",
  priceLabel: "Check retailer",
  evidence: "listing",
  country: "United States",
  checked: "2026-06-27",
  vibes: ["tropical"],
  qualitySignals: ["Peel & stick option", "U.S. storefront"],
  note: "Listing confirmed; price-per-square-foot or product-level review evidence is incomplete.",
  ...item,
});

window.FLOCK_PRODUCTS = [
  // Flamingo collection — 36 distinct patterns.
  product({
    id: "ballerina",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "Wayfair",
    name: "Flamingo in Ballerina Pink",
    price: 38.99,
    coverage: 28,
    rating: 4.4,
    reviews: 52,
    quality: 90,
    bathroom: true,
    madeInUSA: true,
    award: "Best review evidence",
    image: "https://assets.wfcdn.com/im/13686223/resize-h800-p1-w800%5Ecompr-r85/1235/123593746/Flamingo%2BPeel%2Band%2BStick%2BWallpaper-292052534.jpg",
    sourceUrl: "https://www.wayfair.com/decor-pillows/pdp/bayou-breeze-flamingo-peel-and-stick-wallpaper-w000869120.html",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Repositionable", "Steam resistant", "Wipe clean", "Made in USA"],
    note: "The strongest balance of established reviews, material detail, and moderate pricing.",
    color: "#e98f9c",
    background: "#f4ddd4",
    evidence: "verified",
  }),
  product({
    id: "cheeky-pink",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "Home Depot",
    name: "Cheeky Pink Flamingo",
    price: 35.99,
    coverage: 28,
    rating: 3.2,
    reviews: 10,
    quality: 83,
    bathroom: true,
    madeInUSA: true,
    image: "https://tempaper.com/cdn/shop/products/flamingos_cheeky_pink_fl538_1_1020x_progressive_jpg.webp?v=1754944907",
    sourceUrl: "https://www.homedepot.com/p/308998902",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Certified vinyl", "Steam resistant", "Repositionable", "Made in USA"],
    note: "Strong material specifications, with mixed installation and dye-lot feedback.",
    color: "#d95270",
    background: "#f3d8cf",
    evidence: "verified",
  }),
  product({
    id: "pastel-pink-blue",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "Tempaper",
    name: "Pastel Pink & Blue Flamingos",
    price: 59.99,
    coverage: 28.18,
    quality: 88,
    bathroom: true,
    madeInUSA: true,
    image: "https://tempaper.com/cdn/shop/products/FL15127-pink-blue-flamingos-peel-stick-wallpaper.jpg?v=1754944907",
    sourceUrl: "https://tempaper.com/products/flamingo-peel-stick-wallpaper",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Certified vinyl", "Steam resistant", "Sample available", "Made in USA"],
    note: "A coastal colorway with strong specifications; product-level reviews were not visible.",
    color: "#d8788f",
    background: "#bad9df",
    evidence: "price",
  }),
  product({
    id: "daydream-cactus",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "Tempaper",
    name: "Flamingo Daydream — Cactus Rose",
    price: 27.99,
    coverage: 28.18,
    rating: 3.5,
    reviews: 2,
    quality: 86,
    bathroom: true,
    madeInUSA: true,
    image: "https://tempaper.com/cdn/shop/products/FD15080-green-flamingo-daydream-peel-stick-wallpaper_474d1e7a-5193-4983-a7e2-6da05cda0b19.jpg?v=1723146379",
    sourceUrl: "https://tempaper.com/products/flamingo-daydream-peel-stick-wallpaper",
    reviewUrl: "https://www.walmart.com/ip/2070825913",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Certified vinyl", "Moisture friendly", "Wipe clean", "Made in USA"],
    note: "Good materials and price, but the published review sample remains too small for confidence.",
    color: "#d85c69",
    background: "#e8f0df",
    evidence: "verified",
  }),
  product({
    id: "daydream-sunset",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "Tempaper",
    name: "Flamingo Daydream — Pink Sunset",
    price: 59.99,
    coverage: 28.18,
    quality: 86,
    bathroom: true,
    madeInUSA: true,
    sourceUrl: "https://tempaper.com/products/flamingo-daydream-peel-stick-wallpaper",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Certified vinyl", "Moisture friendly", "Wipe clean", "Made in USA"],
    priceLabel: "$59.99 per roll",
    color: "#ee896f",
    background: "#f3bdad",
    evidence: "price",
  }),
  product({
    id: "salinas-land",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper × She She",
    retailer: "Target",
    name: "Flamingo Salinas — Land",
    price: 38.49,
    coverage: 28,
    rating: 4.67,
    reviews: 6,
    quality: 96,
    bathroom: true,
    madeInUSA: true,
    award: "Best material spec",
    image: "https://tempaper.com/cdn/shop/products/FS4159-she-she-pink-flamingo-salinas-removable-wallpaper.jpg?v=1699032995",
    sourceUrl: "https://www.target.com/p/-/A-92370007",
    vibes: ["jungle", "mid-century"],
    qualitySignals: ["Certified vinyl", "Steam resistant", "Wipe clean", "Made in USA"],
    note: "The richest specification sheet in the flamingo collection; review volume is still early.",
    color: "#e76c43",
    background: "#191b19",
    evidence: "verified",
  }),
  product({
    id: "pink-flamingo-beach",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "NuWallpaper",
    retailer: "Home Depot",
    name: "Pink Flamingo Beach",
    price: 29.81,
    coverage: 30.75,
    rating: 4.8,
    reviews: 8,
    quality: 92,
    bathroom: true,
    award: "Best verified value",
    image: "https://bhf-cdn.azureedge.net/bhf-blob-prod/0047011_pink-flamingo-beach-peel-and-stick-wallpaper.jpeg",
    sourceUrl: "https://www.homedepot.com/p/314013686",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Premium vinyl", "Repositionable", "Residue-free", "Washable"],
    note: "A strong normalized price and high rating, with a modest review sample.",
    color: "#df7d8b",
    background: "#e8f0df",
    evidence: "verified",
  }),
  product({
    id: "messner",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Bayou Breeze",
    retailer: "Wayfair",
    name: "Messner Flamingo Beach",
    price: 25.99,
    coverage: 25,
    rating: 4.5,
    reviews: 33,
    quality: 88,
    bathroom: false,
    sourceUrl: "https://www.wayfair.com/decor-pillows/pdp/bayou-breeze-messner-flamingo-beach-18-l-x-205-w-peel-and-stick-wallpaper-roll-w003214338.html",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Repositionable", "Residue-free", "Smooth vinyl", "Drop match"],
    note: "A competitive price with established reviews; moisture performance is not clearly specified.",
    color: "#e87f8d",
    background: "#e3eedb",
    evidence: "verified",
  }),
  product({
    id: "butros",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Bayou Breeze",
    retailer: "Wayfair",
    name: "Butros Tropical Flamingos",
    price: 30.99,
    coverage: 28.91,
    rating: 4.3,
    reviews: 6,
    quality: 80,
    sourceUrl: "https://www.wayfair.com/decor-pillows/pdp/bayou-breeze-butros-peel-and-stick-wallpaper-tropical-flamingos-pink-roll-xeaw1135.html",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Thicker vinyl", "Straight match", "Non-translucent", "Beginner-friendly"],
    color: "#d96b77",
    background: "#dce9d6",
    evidence: "verified",
  }),
  product({
    id: "dupont",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Dovecove",
    retailer: "Wayfair",
    name: "Dupont Soaring Flamingos",
    price: 69.99,
    coverage: 8,
    rating: 4,
    reviews: 24,
    quality: 84,
    bathroom: true,
    madeInUSA: true,
    sourceUrl: "https://www.wayfair.com/decor-pillows/pdp/dovecove-dupont-flamingo-peel-and-stick-wallpaper-roll-w001045519.html",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Matte vinyl", "Water resistant", "Non-toxic inks", "Made in USA"],
    note: "Solid materials, but the small roll produces a high normalized project cost.",
    color: "#d66780",
    background: "#b8d6dc",
    evidence: "verified",
  }),
  product({
    id: "palm-beach",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "NextWall",
    retailer: "Home Depot",
    name: "Palm Beach Flamingo Tropical",
    price: 34.99,
    coverage: 30.75,
    quality: 88,
    bathroom: true,
    madeInUSA: true,
    sourceUrl: "https://www.homedepot.com/p/316138623",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Satin vinyl", "Repositionable", "Residue-free", "Made in USA"],
    priceLabel: "$34.99 per roll",
    color: "#e9919a",
    background: "#c9e2df",
    evidence: "price",
  }),
  product({
    id: "serene-golden-sunrise",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Red Barrel Studio",
    retailer: "Wayfair",
    name: "Serene Flamingos at Golden Sunrise",
    quality: 78,
    sourceUrl: "https://www.wayfair.com/decor-pillows/pdp/red-barrel-studio-flamingo-peel-and-stick-wallpaper-serene-tropical-beach-flamingos-golden-sunrise-vibrant-flowers-wall-murals-69h-x-96w-removable-pvc-wall-paper-self-adhesive-wall-decor-for-bedroom-living-room-hotel-cafe-resort-w118583271.html",
    vibes: ["tropical"],
    qualitySignals: ["Self-adhesive PVC", "Mural format", "Removable", "U.S. retailer"],
    color: "#f19b74",
    background: "#efd89d",
  }),
  product({
    id: "holli-zollinger",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Holli Zollinger",
    retailer: "Wayfair",
    name: "Holli Zollinger Flamingo",
    quality: 84,
    madeInUSA: true,
    sourceUrl: "https://www.refinery29.com/en-us/shop/product/holli-zollinger-flamingo-peel-stick-wallpaper-roll-149927",
    vibes: ["mid-century", "tropical"],
    qualitySignals: ["Matte vinyl", "Washable", "Repositionable", "Made in USA"],
    color: "#d97986",
    background: "#efe0d7",
  }),
  product({
    id: "tropical-palm-leaves",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "AmazingWalls",
    retailer: "Etsy",
    name: "Tropical Palm Leaves Flamingo",
    quality: 86,
    madeInUSA: true,
    priceLabel: "From $6 sample",
    sourceUrl: "https://www.etsy.com/listing/1211521468/flamingo-peel-and-stick-wallpaper",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Washable vinyl", "Repositionable", "GREENGUARD Gold ink", "Made in USA"],
    note: "Made-to-order listing confirmed; sample pricing is not used for square-foot comparison.",
    color: "#e66d75",
    background: "#cfe1cf",
  }),
  product({
    id: "coastal-flamingo-mural",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "CoverMEwallpapers",
    retailer: "Etsy",
    name: "Coastal Flamingo Botanical Mural",
    priceLabel: "From $20",
    sourceUrl: "https://www.etsy.com/listing/4306175674/tropical-flamingo-wallpaper-peel-and",
    vibes: ["tropical"],
    qualitySignals: ["Peel & stick option", "Matte finish", "Custom panels", "U.S. marketplace"],
    color: "#e8888e",
    background: "#e8eee2",
  }),
  product({
    id: "green-leaf-flamingo",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "HomeDecorWallDesign",
    retailer: "Etsy",
    name: "Pink Flamingo & Green Leaf Mural",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/listing/1830627322/tropical-flamingo-wallpaper-peel-and",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Peel & stick vinyl", "Repositionable", "Custom dimensions", "U.S. marketplace"],
    color: "#dc7179",
    background: "#bed8bf",
  }),
  product({
    id: "funky-coastal",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Funky Coastal Flamingo",
    priceLabel: "See material options",
    sourceUrl: "https://www.etsy.com/listing/4323255597/flamingo-wallpaper-peel-and-stick",
    vibes: ["tropical", "mid-century"],
    color: "#e07886",
    background: "#f0d9cc",
  }),
  product({
    id: "vintage-pink-retro",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Vintage Pink Retro Flamingo",
    priceLabel: "From $9.46",
    sourceUrl: "https://www.etsy.com/listing/1206610844/vintage-flamingo-wallpaper-peel-stick",
    vibes: ["mid-century", "tropical"],
    color: "#d98291",
    background: "#e9ddcc",
  }),
  product({
    id: "miami-painting",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Miami-Style Flamingo Painting",
    priceLabel: "From $14.96",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#eb6577",
    background: "#a9d6d6",
  }),
  product({
    id: "tropical-beach-theme",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Tropical Beach Flamingo",
    priceLabel: "From $18.75",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["tropical"],
    color: "#e78a91",
    background: "#d9e8e3",
  }),
  product({
    id: "dark-lotus",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Dark Lotus Tropical Flamingo",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["jungle", "mid-century"],
    color: "#db687a",
    background: "#203e37",
  }),
  product({
    id: "retro-coastal",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Retro Coastal Flamingo",
    priceLabel: "From $20",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#e9838b",
    background: "#c4dbd3",
  }),
  product({
    id: "retro-palm",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Retro Palm Flamingo",
    priceLabel: "From $8.98",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#dc737e",
    background: "#d6c795",
  }),
  product({
    id: "vintage-green-pink",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Vintage Green & Pink Flamingo",
    priceLabel: "From $20.76",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["mid-century", "jungle"],
    color: "#de7581",
    background: "#728c67",
  }),
  product({
    id: "watercolor-flock",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Watercolor Flamingo Flock",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["tropical"],
    color: "#e58d98",
    background: "#f0e7df",
  }),
  product({
    id: "beach-landscape",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Flamingo Beach Landscape Mural",
    priceLabel: "See mural sizes",
    sourceUrl: "https://www.etsy.com/listing/1795037267/flamingo-wallpaper-mural-peel-stick",
    vibes: ["tropical"],
    color: "#e57882",
    background: "#c9dedc",
  }),
  product({
    id: "pink-green-bedroom",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Pink & Green Tropical Flamingos",
    priceLabel: "See panel sizes",
    sourceUrl: "https://www.etsy.com/listing/4403620771/peel-and-stick-tropical-flamingo",
    vibes: ["tropical", "jungle"],
    color: "#dd6f7e",
    background: "#a9c5a5",
  }),
  product({
    id: "boho-neutral",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Boho Neutral Flamingo EW264",
    priceLabel: "From $10.50",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century"],
    color: "#c8807d",
    background: "#e7ddce",
  }),
  product({
    id: "peony-nursery",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Flamingo & Peony Floral",
    priceLabel: "From $6 sample",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical"],
    color: "#e58d9e",
    background: "#f0d9de",
  }),
  product({
    id: "whimsical-safari",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Whimsical Jungle Safari Flamingo",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["jungle"],
    color: "#e77c80",
    background: "#294e3e",
  }),
  product({
    id: "exotic-toucan-flamingo",
    collection: "flamingo",
    species: "Flamingo + Toucan",
    manufacturer: "Ambesonne",
    retailer: "Walmart",
    name: "Exotic Toucan & Flamingo Floral",
    quality: 74,
    sourceUrl: "https://www.walmart.com/ip/5331337211",
    vibes: ["tropical", "jungle"],
    qualitySignals: ["Self-adhesive", "Cut-to-fit", "Multiple sizes", "U.S. retailer"],
    color: "#dc6572",
    background: "#8fc7d5",
  }),
  product({
    id: "flamingo-fantasy",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Tempaper",
    retailer: "DecoratorsBest",
    name: "Flamingo Fantasy Light Pink",
    price: 19.99,
    coverage: 28,
    quality: 86,
    bathroom: true,
    madeInUSA: true,
    sourceUrl: "https://www.decoratorsbest.com/products/tempaper-flamingo-fantasy-light-pink-peel-and-stick-wallpaper-28-sq-ft",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Class A fire rated", "Steam resistant", "Wipe clean", "Made in USA"],
    note: "Strong clearance value when in stock; the listing was marked unavailable when checked.",
    color: "#e28d98",
    background: "#f0e1dd",
    evidence: "price",
  }),
  product({
    id: "geometric-flamingo",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "MAIA HOMES",
    retailer: "MAIA HOMES",
    name: "Geometric Tropical Pink Flamingo",
    quality: 80,
    sourceUrl: "https://maiahomes.com/collections/safari-wallpaper/products/geometric-tropical-pink-flamingo-removable-wallpaper",
    vibes: ["mid-century", "tropical"],
    qualitySignals: ["Peel & stick option", "Custom sizing", "Vinyl material", "U.S. checkout"],
    color: "#d76e79",
    background: "#243f39",
  }),
  product({
    id: "summer-flamingo-palm",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Summer Flamingo & Palm",
    priceLabel: "See panel sizes",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#df6d7a",
    background: "#edc16f",
  }),
  product({
    id: "botanical-flamingo-garden",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Botanical Flamingo Garden",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["jungle", "tropical"],
    color: "#dc7781",
    background: "#9ebd97",
  }),
  product({
    id: "pink-lagoon-flamingos",
    collection: "flamingo",
    species: "Flamingo",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Pink Lagoon Flamingos",
    priceLabel: "See mural sizes",
    sourceUrl: "https://www.etsy.com/market/flamingo_peel_stick_wallpaper",
    vibes: ["tropical"],
    color: "#d76d82",
    background: "#b6d9d8",
  }),

  // Wild-bird collection — 36 distinct patterns.
  product({
    id: "birds-paradise",
    collection: "wild-bird",
    species: "Parrot · Toucan · Cockatoo",
    manufacturer: "Tempaper",
    retailer: "Walmart",
    name: "Birds of Paradise — Rainforest Green",
    price: 35.99,
    coverage: 28,
    rating: 4.7,
    reviews: 11,
    quality: 92,
    bathroom: true,
    madeInUSA: true,
    award: "Best tropical bird",
    sourceUrl: "https://www.walmart.com/ip/7245900169",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Repositionable", "Steam resistant", "Wipe clean", "Made in USA"],
    note: "The leading wild-bird option for balanced price, specifications, and review evidence.",
    color: "#ef8e3e",
    background: "#28583d",
    evidence: "verified",
  }),
  product({
    id: "bird-watching-sea",
    collection: "wild-bird",
    species: "Songbird",
    manufacturer: "Tempaper × Cynthia Rowley",
    retailer: "Lowe's",
    name: "Bird Watching — Sea",
    rating: 4.3,
    reviews: 39,
    quality: 90,
    bathroom: true,
    madeInUSA: true,
    priceLabel: "Check Lowe's",
    sourceUrl: "https://www.lowes.com/pd/Tempaper-Bird-Watching-Sea-Peel-and-Stick-Wallpaper/5013610793",
    vibes: ["jungle", "mid-century"],
    qualitySignals: ["Premium vinyl", "Repositionable", "Steam resistant", "Made in USA"],
    note: "The largest verified review sample in the wild-bird collection, with some pattern-alignment concerns.",
    color: "#d0b785",
    background: "#416f71",
    evidence: "reviews",
  }),
  product({
    id: "mayflower-flight",
    collection: "wild-bird",
    species: "Finch",
    manufacturer: "Mayflower",
    retailer: "US Wall Decor",
    name: "Birds in Flight — Black & White",
    price: 82,
    coverage: 20.25,
    quality: 91,
    bathroom: false,
    madeInUSA: true,
    sourceUrl: "https://uswalldecor.com/products/md10014-mayflower-birds-in-flight-peel-stick-wallpaper-black-white",
    vibes: ["mid-century"],
    qualitySignals: ["Premium paper", "Repositionable", "Washable", "Made in USA"],
    note: "Premium U.S.-made material with a high normalized price and no visible product reviews.",
    color: "#e8e3d7",
    background: "#172c28",
    evidence: "price",
  }),
  product({
    id: "tropical-birds-black",
    collection: "wild-bird",
    species: "Tropical birds",
    manufacturer: "Graham & Brown",
    retailer: "Target",
    name: "Transform Tropical Birds — Black",
    price: 29.99,
    coverage: 30,
    quality: 80,
    sourceUrl: "https://www.target.com/p/-/A-90276912",
    vibes: ["jungle", "mid-century"],
    qualitySignals: ["Removable", "Wipe clean", "Smooth surfaces", "U.S. retailer"],
    color: "#e6a85f",
    background: "#1f2924",
    evidence: "price",
  }),
  product({
    id: "veelike-exotic",
    collection: "wild-bird",
    species: "Exotic birds",
    manufacturer: "VEELIKE",
    retailer: "Walmart",
    name: "Exotic Birds, Fruit & Jungle Leaves",
    price: 16.99,
    coverage: 14.5,
    rating: 4.5,
    reviews: 18,
    quality: 78,
    bathroom: true,
    sourceUrl: "https://www.walmart.com/ip/3930710218",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Thick vinyl", "Matte finish", "Water resistant", "U.S. retailer"],
    color: "#d4a33f",
    background: "#183f34",
    evidence: "verified",
  }),
  product({
    id: "harry-grace-aqua",
    collection: "wild-bird",
    species: "Tropical birds",
    manufacturer: "Harry & Grace",
    retailer: "Walmart",
    name: "Aqua Tropical Bird",
    price: 59.99,
    coverage: 30.75,
    quality: 85,
    sourceUrl: "https://www.walmart.com/ip/2620991781",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Satin vinyl", "Repositionable", "Residue-free", "U.S. retailer"],
    color: "#e68a54",
    background: "#8fc9c7",
    evidence: "price",
  }),
  product({
    id: "arthouse-bird-garden",
    collection: "wild-bird",
    species: "Garden birds",
    manufacturer: "NextWall",
    retailer: "Walmart",
    name: "Arthouse Bird Garden",
    priceLabel: "Check Walmart",
    quality: 84,
    sourceUrl: "https://www.walmart.com/search?q=NextWall+Arthouse+Bird+Garden+Peel+and+Stick+Wallpaper",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Self-adhesive vinyl", "Repositionable", "Removable", "U.S. retailer"],
    color: "#d49857",
    background: "#d9e3d5",
  }),
  product({
    id: "cuban-tropicana",
    collection: "wild-bird",
    species: "Cockatoo · Toucan · Songbird",
    manufacturer: "Independent brand",
    retailer: "Walmart",
    name: "Cuban Tropicana Birds",
    quality: 74,
    sourceUrl: "https://www.walmart.com/ip/17679709199",
    vibes: ["jungle", "mid-century"],
    qualitySignals: ["Self-adhesive", "Removable", "Contact-paper format", "U.S. retailer"],
    color: "#ef765c",
    background: "#1c2e2b",
  }),
  product({
    id: "kanworse-parrot-toucan",
    collection: "wild-bird",
    species: "Parrot · Toucan",
    manufacturer: "Kanworse",
    retailer: "Walmart",
    name: "Botanical Jungle Parrot & Toucan",
    quality: 74,
    sourceUrl: "https://www.walmart.com/ip/19728968046",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Self-adhesive", "Removable", "Multiple sizes", "U.S. retailer"],
    color: "#f2a245",
    background: "#275846",
  }),
  product({
    id: "ambesonne-toucan",
    collection: "wild-bird",
    species: "Toucan",
    manufacturer: "Ambesonne",
    retailer: "Walmart",
    name: "Toucan Birds & Flowers Plot",
    quality: 75,
    sourceUrl: "https://business.walmart.com/ip/Ambesonne-Tropical-Peel-Stick-Wallpaper-for-Home-Toucan-Birds-Flowers-Plot-13-x72-Olive-Green-and-Orange/10284014141",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Self-adhesive", "Multiple lengths", "Cut-to-fit", "U.S. retailer"],
    color: "#e98b42",
    background: "#536943",
  }),
  product({
    id: "ambesonne-hummingbird",
    collection: "wild-bird",
    species: "Hummingbird",
    manufacturer: "Ambesonne",
    retailer: "Walmart",
    name: "Hummingbirds Exotic Art",
    quality: 75,
    sourceUrl: "https://www.walmart.com/search?q=Ambesonne+Tropical+Hummingbirds+Exotic+Art+Peel+Stick+Wallpaper",
    vibes: ["tropical"],
    qualitySignals: ["Self-adhesive", "Multiple lengths", "Cut-to-fit", "U.S. retailer"],
    color: "#dd9c4d",
    background: "#263d52",
  }),
  product({
    id: "hawaiian-parrot",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "MuralsPrint",
    retailer: "Walmart",
    name: "Hawaiian Tropical Parrot",
    quality: 78,
    bathroom: true,
    sourceUrl: "https://business.walmart.com/ip/MuralsPrint-Hawaiian-Tropical-Parrot-Peel-and-Stick-Wallpaper-10-ft-H-x-24-inch-W/264347652",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Washable", "Custom panel", "Self-adhesive", "U.S. retailer"],
    color: "#ec7b4a",
    background: "#20503b",
  }),
  product({
    id: "vintage-animal-toucan",
    collection: "wild-bird",
    species: "Crane · Parrot · Toucan",
    manufacturer: "Independent brand",
    retailer: "Walmart",
    name: "Vintage Botanical Wild Birds",
    quality: 74,
    sourceUrl: "https://business.walmart.com/ip/Peel-Stick-Wallpaper-Canvas-Tropical-Vintage-Botanical-Wild-Animal-Crane-Parrot-Toucan-Monkey-Palm-Modern-Art-Wall-Mural-Decor-Self-Adhesive-Removabl/16788160617",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["Canvas mural", "Self-adhesive", "Removable", "U.S. retailer"],
    color: "#e99156",
    background: "#273f35",
  }),
  product({
    id: "geometry-love-birds",
    collection: "wild-bird",
    species: "Lovebird",
    manufacturer: "Spoonflower",
    retailer: "Etsy",
    name: "Geometry of Love Birds",
    rating: 4.5,
    quality: 89,
    madeInUSA: true,
    priceLabel: "See roll sizes",
    sourceUrl: "https://www.etsy.com/listing/1445762886/mid-century-birds-removable-peel-and",
    vibes: ["mid-century"],
    qualitySignals: ["PVC-free", "Linen texture", "Repositionable", "Printed in USA"],
    note: "A clearly specified U.S.-printed mid-century option; exact roll price varies by length.",
    color: "#e39a4e",
    background: "#355a58",
    evidence: "reviews",
  }),
  product({
    id: "monkey-parrot-fern",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Monkeys, Parrot & Fern",
    priceLabel: "From $12",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle"],
    color: "#e88b43",
    background: "#214839",
  }),
  product({
    id: "palm-birds-chinoiserie",
    collection: "wild-bird",
    species: "Tropical birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Tropical Chinoiserie Palm & Birds",
    priceLabel: "From $14.70",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#e5a24c",
    background: "#9eb9a4",
  }),
  product({
    id: "golden-look-bird",
    collection: "wild-bird",
    species: "Tropical bird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Golden Look Tropical Bird",
    priceLabel: "From $4.80",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#e8bb58",
    background: "#273e35",
  }),
  product({
    id: "japanese-crane",
    collection: "wild-bird",
    species: "Crane",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Vintage Japanese Crane",
    priceLabel: "From $2.99",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#dca650",
    background: "#29485a",
  }),
  product({
    id: "green-jungle-parrots",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Exotic Green Jungle Parrots",
    priceLabel: "From $9.75",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle"],
    color: "#e98642",
    background: "#17503a",
  }),
  product({
    id: "minty-bird-paradise",
    collection: "wild-bird",
    species: "Bird of paradise",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Minty Birds of Paradise",
    priceLabel: "From $16",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#f09b48",
    background: "#a9d4c6",
  }),
  product({
    id: "hummingbird-lemon",
    collection: "wild-bird",
    species: "Hummingbird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Hummingbird & Lemon Tree",
    priceLabel: "From $8",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#d29d43",
    background: "#eee0a6",
  }),
  product({
    id: "rainforest-bird",
    collection: "wild-bird",
    species: "Tropical bird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Vintage Rainforest Bird",
    priceLabel: "From $20.80",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "tropical"],
    color: "#e59145",
    background: "#294b3a",
  }),
  product({
    id: "victorian-birds",
    collection: "wild-bird",
    species: "Garden birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Dark Victorian Birds & Flowers",
    priceLabel: "From $2.50",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "mid-century"],
    color: "#d5aa5e",
    background: "#222d2a",
  }),
  product({
    id: "navy-exotic-birds",
    collection: "wild-bird",
    species: "Exotic birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Dark Navy Exotic Birds",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "mid-century"],
    color: "#e7a24f",
    background: "#183149",
  }),
  product({
    id: "birds-blossoms",
    collection: "wild-bird",
    species: "Chinoiserie birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Chinoiserie Birds & Blossoms",
    priceLabel: "From $14.30",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#df9862",
    background: "#aac6ba",
  }),
  product({
    id: "dark-tropical-bird",
    collection: "wild-bird",
    species: "Tropical bird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Dark Tropical Jungle Bird",
    priceLabel: "From $12.10",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle"],
    color: "#ed8a42",
    background: "#153b2f",
  }),
  product({
    id: "birds-in-trees",
    collection: "wild-bird",
    species: "Tropical birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Birds in the Trees WIV 706",
    priceLabel: "From $5",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["tropical", "jungle"],
    color: "#e79b48",
    background: "#577e65",
  }),
  product({
    id: "parrots-tropical-tree",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "WallpaperStudio",
    retailer: "Etsy",
    name: "Parrots Tropical Tree CC035",
    priceLabel: "See panel sizes",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "tropical"],
    color: "#f39a3e",
    background: "#1d5039",
  }),
  product({
    id: "oriental-peacock",
    collection: "wild-bird",
    species: "Peacock",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Oriental Peacock",
    priceLabel: "From $11.20",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "mid-century"],
    color: "#daa64c",
    background: "#1d5960",
  }),
  product({
    id: "colorful-parrot-mural",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Colorful Tropical Parrot Mural",
    priceLabel: "From $22.99",
    sourceUrl: "https://www.etsy.com/listing/1810334116/tropical-removable-vinyl-mural-peel-and",
    vibes: ["jungle", "tropical"],
    color: "#f07763",
    background: "#264b39",
  }),
  product({
    id: "parrot-rv017",
    collection: "wild-bird",
    species: "Parrot",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Botanical Tropical Parrot RV017",
    priceLabel: "From $9",
    sourceUrl: "https://www.etsy.com/market/tropical_birds_peel_and_stick_wallpaper",
    vibes: ["jungle", "tropical"],
    color: "#eb8052",
    background: "#305c45",
  }),
  product({
    id: "terracotta-line-bird",
    collection: "wild-bird",
    species: "Tropical bird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Terracotta Line-Art Jungle Bird",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/listing/4307869482/minimal-tropical-bird-wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#bd664d",
    background: "#ead9c8",
  }),
  product({
    id: "island-summer-birds",
    collection: "wild-bird",
    species: "Paradise birds",
    manufacturer: "Spoonflower",
    retailer: "Etsy",
    name: "Bright Jungle Birds — Island Summer",
    priceLabel: "From $7.20",
    quality: 88,
    madeInUSA: true,
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["jungle", "tropical"],
    qualitySignals: ["PVC-free", "Linen texture", "Repositionable", "Printed in USA"],
    color: "#ed8251",
    background: "#2d6a54",
  }),
  product({
    id: "blue-heron-pv025",
    collection: "wild-bird",
    species: "Blue heron",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Blue Heron PV025",
    priceLabel: "From $17",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#d9a45a",
    background: "#466c7d",
  }),
  product({
    id: "flying-swallows",
    collection: "wild-bird",
    species: "Swallow",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Flying Swallows in Flight",
    priceLabel: "From $6",
    sourceUrl: "https://www.etsy.com/market/bird_peel_and_stick_wallpaper",
    vibes: ["mid-century"],
    color: "#d39c52",
    background: "#c9d8d2",
  }),
  product({
    id: "great-blue-heron",
    collection: "wild-bird",
    species: "Great blue heron",
    manufacturer: "Love vs. Design",
    retailer: "Etsy",
    name: "Great Blue Heron Chinoise",
    priceLabel: "From $6 sample",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical", "mid-century"],
    qualitySignals: ["Custom colors", "Peel & stick option", "Sample available", "U.S. marketplace"],
    color: "#d5a45c",
    background: "#345f78",
  }),
  product({
    id: "tropical-plant-parrots",
    collection: "wild-bird",
    species: "Parrot · Toucan",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Watercolor Tropical Birds & Plants",
    priceLabel: "See panel sizes",
    sourceUrl: "https://www.etsy.com/listing/1145866747/tropical-birds-and-plants-wallpaper-peel",
    vibes: ["jungle", "tropical"],
    color: "#f0805d",
    background: "#cce0cb",
  }),
  product({
    id: "toucan-jungle-pattern",
    collection: "wild-bird",
    species: "Parrot · Toucan",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Toucan & Parrot Jungle Pattern",
    priceLabel: "See material options",
    sourceUrl: "https://www.etsy.com/listing/1375585687/tropical-leaves-wallpaper-with-birds",
    vibes: ["jungle", "tropical"],
    color: "#f1a13e",
    background: "#24533b",
  }),
  product({
    id: "watercolor-cockatoo",
    collection: "wild-bird",
    species: "Parrot · Cockatoo · Toucan",
    manufacturer: "Pickwick and Elm",
    retailer: "Etsy",
    name: "Watercolor Tropical Bird Branches",
    priceLabel: "See panel sizes",
    sourceUrl: "https://www.etsy.com/listing/4457286810/watercolor-tropical-bird-wallpaper",
    vibes: ["tropical", "jungle"],
    color: "#e98859",
    background: "#d8e0c8",
  }),
  product({
    id: "navy-bird-paradise",
    collection: "wild-bird",
    species: "Bird of paradise",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Navy Linen Bird of Paradise",
    priceLabel: "From $14.17",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#e3a046",
    background: "#1f3b5a",
  }),
  product({
    id: "pink-palm-exotic-bird",
    collection: "wild-bird",
    species: "Exotic bird",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Pink Palm Exotic Bird",
    priceLabel: "From $3.59",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#e98e58",
    background: "#e8bab9",
  }),
  product({
    id: "beige-peacock-palms",
    collection: "wild-bird",
    species: "Peacock",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Beige Palm & Peacock A128",
    priceLabel: "See size options",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century", "tropical"],
    color: "#c99149",
    background: "#ded3bc",
  }),
  product({
    id: "zen-birds-ocean",
    collection: "wild-bird",
    species: "Coastal birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Zen Birds Above the Ocean",
    priceLabel: "From $14.66",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century"],
    color: "#d3a557",
    background: "#9eb9b9",
  }),
  product({
    id: "cherry-blossom-birds",
    collection: "wild-bird",
    species: "Garden birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Cherry Blossom Birds",
    priceLabel: "From $9",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["tropical", "mid-century"],
    color: "#d8a25c",
    background: "#e9c6ca",
  }),
  product({
    id: "forest-birds-white",
    collection: "wild-bird",
    species: "Forest birds",
    manufacturer: "Independent maker",
    retailer: "Etsy",
    name: "Forest Birds on White",
    priceLabel: "From $5",
    sourceUrl: "https://www.etsy.com/market/peel_and_stick_tropical_bird_wallpaper",
    vibes: ["mid-century"],
    color: "#bd8e4d",
    background: "#e8e8df",
  }),
];
